/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-107020-ga7e0997324-20220530"
#endif /* AVUTIL_FFVERSION_H */
